// const movies = [
//     {
//      "title": "The Unfamiliar",
//      "title_local": "Mượn Xác",
//      "rating": "c18",
//      "length": "87",
//      "producer": "Dark Matter Studios",
//      "country": "Anh",
//      "genre": "Kinh dị",
//      "actor": "Jemima West, Christopher Dane",
//      "director": "Henk Pretorius",
//      "openDate": "18/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/14/300_1600068064807.jpg",
//      "trailer": "https://www.youtube.com/watch?v=kZfW4gd6Ams",
//      "summary": "Một nữ bác sĩ phục vụ trong quân đội nước Anh trở về nhà sau chiến tranh. Thời gian này, cô thường gặp nhiều ảo giác kỳ lạ. Tưởng chừng đấy chỉ là những tổn thương về mặt tâm lý, nhưng sự thật đáng sợ rằng đang có một thế lực tà ác bí ẩn ám vào cô."
//     },
//     {
//      "title": "Bigfoot Family",
//      "title_local": "Gia Đình Chân To Phiêu Lưu Ký",
//      "rating": "c18",
//      "length": "0",
//      "producer": "Charades",
//      "director": "Jeremy Degruson, Ben Stassen",
//      "genre": "Hoạt hình",
//      "actor": "Alexis Victor, Kylian Trouillard",
//      "country": "Bỉ",
//      "openDate": "19/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/18/300-big_1600398661361.jpg",
//      "trailer": "https://www.youtube.com/watch?v=cFAfDRwQAhI",
//      "summary": "Tiếp nối phần phim Bố Tớ Là Chân To, lần này chuyện phim dẫn dắt người xem đi theo gia đình Chân To và cuộc chiến chống lại những kẻ đang phá hoại môi trường. Liệu họ có thành công ngăn chặn được âm mưu của kẻ ác không?"
//     },
//     {
//      "title": "The Magic Kids: Three Unlikely Heroes",
//      "title_local": "Xứ Sở Phép Thuật",
//      "rating": "c18",
//      "length": "97",
//      "producer": "Rat Pack Filmproduktion",
//      "genre": "Phiêu lưu, Gia đình, Thần thoại",
//      "country": "Đức",
//      "actor": "Christian Berkel, Butz Ulrich Buse",
//      "director": "Tim Trageser",
//      "openDate": "18/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/15/11_1600175675192.jpg",
//      "trailer": "https://www.youtube.com/watch?v=RWdEcMBGN0g",
//      "summary": "Ma cà rồng sợ máu, người sói bị dị ứng lông và cô tiên có cánh nhưng lại mắc bệnh sợ độ cao... Ba đứa trẻ tréo ngoe ấy thường xuyên bị bạn bè tại trường phép thuật chọc ghẹo vì những chứng bệnh chẳng giống ai. Thế nhưng, chính họ là những kẻ duy nhất phát hiện ra âm mưu hủy diệt thị trấn của lão thị trưởng xấu xa."
//     },
//     {
//      "title": "Oh! My Gran",
//      "title_local": "Bà Tôi Là Công Chúa",
//      "rating": "c16",
//      "length": "110",
//      "producer": "CGV Arthouse",
//      "director": "Jung Se Kyo",
//      "genre": "Hài, Tâm lý",
//      "country": "Hàn Quốc",
//      "actor": "Na Moon Hee, Lee Hee Joon",
//      "openDate": "18/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/14/300wx450h_1600069590182.jpg",
//      "trailer": "https://www.youtube.com/watch?v=Z8o4GYAty6E",
//      "summary": "Moon Hee là một bà cụ bị mắc bệnh Alzheimer, bà cứ nghĩ bản thân mình là nàng công chúa trong phim hoạt hình. Trong lần ra ngoài, cháu gái của bà là Bo Mi gặp tai nạn, tuy nhiên công cuộc điều tra của cảnh sát trở nên khó khăn khi bà Moon Hee là nhân chứng duy nhất."
//     },
//     {
//      "title": "Invasion",
//      "title_local": "Phòng Thủ Địa Cầu",
//      "rating": "c13",
//      "length": "133",
//      "country": "Nga",
//      "director": "Fedor Bondarchuk",
//      "actor": "Alexander Petrov, Irina Starshenbaum",
//      "genre": "Hành động, Giả Tưởng",
//      "producer": "Art Pictures Studio",
//      "openDate": "18/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/14/300-in_1600068785828.jpg",
//      "trailer": "https://www.youtube.com/watch?v=gZ-p81xWMGk",
//      "summary": "Sau cuộc đụng độ với người ngoài hành tinh, một cô gái đã vô tình sở hữu năng lực mang sức mạnh kỳ dị. Chính điều này khiến cho những tộc người ngoài Trái Đất quay trở lại tiêu diệt cô, người mà họ cho rằng sẽ là mối đe dọa đầy nguy hiểm."
//     },
//     {
//      "title": "Hunter's Moon",
//      "title_local": "Bẫy Trăng Máu",
//      "rating": "c18",
//      "length": "82",
//      "genre": "Tội phạm, Kinh dị, Ly kì",
//      "actor": "Katrina Bowden, Jay Mohr",
//      "country": "Mỹ",
//      "producer": "BondIt Media Capital",
//      "director": "Michael Caissie",
//      "openDate": "18/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/11/300-bay_1599818995293.jpg",
//      "trailer": "https://www.youtube.com/watch?v=RlC7IWbmkko",
//      "summary": "Ba cô nàng tuổi teen tổ chức tiệc tại nhà trong lúc bố mẹ đi vắng. Họ bị một nhóm thanh niên quấy rối và phải nhờ đến cảnh sát giúp đỡ. Khi tới nơi, phía cảnh sát phát hiện có điều bất ổn xung quanh ngôi nhà. Liệu rằng bí mật kinh hoàng nào đang bị che giấu?"
//     },
//     {
//      "title": "Jungle Beat: The Movie",
//      "title_local": "Vì Sao Đưa Bạn Tới",
//      "rating": "c18",
//      "length": "88",
//      "country": "Mauritius",
//      "producer": "Sandcastle Studios",
//      "director": "Brent Dawes",
//      "actor": "David Menkin, David Rintoul",
//      "genre": "Hoạt hình, Gia đình, Phiêu lưu",
//      "openDate": "18/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/7/300-vi-sao_1599468355422.jpg",
//      "trailer": "https://www.youtube.com/watch?v=ATYw68y5Phk",
//      "summary": "Phim là câu chuyện vui tươi về những loài động vật trong rừng xanh. Một ngày nọ, chú khỉ tinh nghịch cùng nàng voi đáng yêu chạm mặt người bạn đặc biệt đến từ hành tinh khác, càng đặc biệt hơn là giờ đây chúng đều có thể nói tiếng người."
//     },
//     {
//      "title": "A Mermaid In Paris",
//      "title_local": "Nàng Tiên Cá Ở Paris",
//      "rating": "c13",
//      "length": "110",
//      "genre": "Hài, Giả Tưởng, Tình cảm",
//      "actor": "Nicolas Duvauchelle, Marilyn Lima",
//      "director": "Mathias Malzieu",
//      "country": "Pháp",
//      "openDate": "11/9/2020",
//      "poster": "https://cdnmedia.thethaovanhoa.vn/Upload/B0g2ZnIe48e9au7dkcAV3w/files/000039/0000000000000000000211/00000262/00026/0019/0010/8/Nang%20tien%20ca%20trong.jpg",
//      "trailer": "https://www.youtube.com/embed/EcYhREP1uAM",
//      "summary": "Sau những đổ vỡ trong tình yêu, chàng ca sĩ nghiệp dư Gaspard đã nguyện chẳng yêu ai nữa. Còn với nàng tiên cá Lula, nàng luôn bảo vệ chính mình khỏi tình yêu bằng giọng hát ma mị, khiến cho bất cứ người đàn ông nào nghe thấy đều phải chết. Thế nhưng, dòng sông Seine đã thay đổi tất cả khi cuốn nàng Lula đến với cuộc đời Gaspard trong một cơn thuỷ triều. Và rồi người đàn ông vốn đau khổ vì tình và nàng tiên cá chưa hề biết tới mùi vị tình yêu đã tìm được cách bước vào trái tim nhau. Hai thế giới trở nên đồng điệu trong khúc ca tình yêu của họ."
//     },
//     {
//      "title": "Bloodlust Lady",
//      "title_local": "Ác Nữ",
//      "rating": "c18",
//      "length": "115",
//      "producer": "MVP Pictures",
//      "country": "Indonesia",
//      "director": "Anggy Umbara, Bounty Umbara",
//      "genre": "Kinh dị",
//      "actor": "Indah Permatasari, Arifin Putra",
//      "openDate": "11/9/2020",
//      "movieOpenDate": "11/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/7/300-ac-nu_1599466702426.jpg",
//      "trailer": "https://www.youtube.com/embed/e_1R_OZumFc",
//      "summary": "Ác Nữ là câu chuyện về một oan hồn của một cô gái mặc váy đỏ, cô bị hãm hại bởi một nhóm đàn ông độc ác và quyết định quay trở về báo thù họ."
//     },
//     {
//      "title": "Break The Silence: The Movie",
//      "title_local": "Tâm Tư Cất Lời",
//      "rating": "c18",
//      "length": "94",
//      "country": "Hàn Quốc",
//      "producer": "Big Hit Entertainment",
//      "genre": "Nhạc kịch",
//      "director": "Park Jun Soo",
//      "actor": "BTS",
//      "openDate": "10/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/3/bresak1_1599104381068.jpeg",
//      "trailer": "https://www.youtube.com/embed/QfctZceL6mw",
//      "summary": "Bộ phim hứa hẹn sẽ là “cuốn nhật ký” bằng hình ảnh đầy chân thực, sống động và ngập tràn cảm xúc của nhóm nhạc hàng đầu thế giới, được ghi lại từ chuỗi concert cháy vé Love Yourself: Speak Yourself của BTS trong năm 2019. Đây là bộ phim nối tiếp thành công của bộ ba phim tài liệu ca nhạc rất thành công trước đây của nhóm bao gồm Burn The Stage: The Movie vào năm 2018, Love Yourself in Seoul và Bring The Soul: The Movie cùng năm 2019."
//     },
//     {
//      "title": "Greenland",
//      "title_local": "Thảm Họa Thiên Thạch",
//      "rating": "c16",
//      "length": "120",
//      "director": "Ric Roman Waugh",
//      "producer": "G-BASE",
//      "genre": "Hành động, Ly kì",
//      "actor": "Gerard Butler, Morena Baccarin",
//      "country": "Mỹ",
//      "openDate": "10/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/3/300-green_1599102863973.jpg",
//      "trailer": "https://www.youtube.com/embed/1M8s0w1Fzm4",
//      "summary": "Các mảnh vỡ thiên thạch rơi xuống trái đất, tạo nên thảm họa đe dọa nhân loại. Để có thể sống sót, vùng đất duy nhất mà con người có thể trú ẩn an toàn chính là Greenland. Liệu rằng tận thế có xảy ra hay không?"
//     },
//     {
//      "title": "Deliver Us From Evil",
//      "title_local": "Ác Quỷ Đối Đầu",
//      "rating": "c18",
//      "length": "104",
//      "director": "Scott Derrickson, Won-Chan Hong",
//      "actor": "Eric Bana,  Édgar Ramírez, Hwang Jung Min, Lee Jung Jae",
//      "genre": "Kinh dị, Ly kì, Hành động, Tội phạm",
//      "country": "Hàn Quốc",
//      "producer": "Hive Media Corp",
//      "openDate": "4/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/8/27/fb-main-poster-aqdd1_1598525805457.jpg",
//      "trailer": "https://www.youtube.com/embed/KtLXv04nM9s",
//      "summary": "In-Nam là một sát thủ đang sắp giải nghệ thì nhận được tin con gái của mình bị bắt cóc. Kể từ đây, một cuộc chiến diễn ra giữa In-Nam và tên đồ tể máu lạnh có biệt danh là Ray."
//     },
//     {
//      "title": "The New Mutants",
//      "title_local": "Dị Nhân Thế Hệ Mới",
//      "rating": "c16",
//      "length": "94",
//      "actor": "Anya Taylor-Joy, Charlie Heaton, Maisie Williams",
//      "country": "Mỹ",
//      "genre": "Giả Tưởng, Hành động, Phiêu lưu",
//      "director": "Josh Boone",
//      "producer": "Marvel, 20th Century Fox",
//      "openDate": "1/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/5/22/poster-blue_1590120309179.jpg",
//      "trailer": "https://www.youtube.com/embed/W_vJhUAOFpI",
//      "summary": "The New Mutants (Dị Nhân Thế Hệ Mới) là câu chuyện về năm dị nhân trẻ khám phá ra sức mạnh dị phàm của họ trong khi bị giam cầm ở một khu phức hợp. Họ phải chiến đấu để được tự do."
//     },
//     {
//      "title": "Tenet",
//      "title_local": "",
//      "rating": "c16",
//      "length": "150",
//      "producer": "Warner Bros",
//      "country": "Anh",
//      "genre": "Hành động, Giả Tưởng, Ly kì",
//      "director": "Christopher Nolan",
//      "actor": "John David Washington, Elizabeth Debicki, Robert Pattinson",
//      "openDate": "27/8/2020",
//      "poster": "https://galaxycine.vn/media/2020/6/3/mv5bmtc5mzc5n2qtzjkwmy00mjezlwfinwytyjgwyta5mmizyznkxkeyxkfqcgdeqxvymtaxnde3mte5--v1-_1591174007572.jpg",
//      "trailer": "https://www.youtube.com/embed/AZGcmvrTX9M",
//      "summary": "Với cái tên ấn tượng - Tenet, bộ phim mới của Christopher Nolan được kỳ vọng khiến khán giả ồ ạt quay trở lại rạp sau đợt dịch Covid-19. TENET kể về hai nhân vật chính được tổ chức gián điệp tuyển dụng và dấn thân vào thế giới tình báo quốc tế đầy hỗn tạp. Sở hữu công nghệ hiện đại có thể thao túng, nghịch đảo thời gian, họ phải ngăn chặn Thế chiến thứ 3 trước khi xảy ra."
//     },
//     {
//      "title": "Ròm",
//      "title_local": "",
//      "rating": "c18",
//      "length": "79",
//      "genre": "Phiêu lưu, Hành động",
//      "director": "Trần Thanh Huy",
//      "actor": "Trần Anh Khoa, Cát Phượng, Mai Thế Hiệp, Hải Triều",
//      "country": "Việt Nam",
//      "producer": "Hoan Khuê",
//      "openDate": "25/9/2020",
//      "poster": "https://i.ytimg.com/vi/XRm1P7oGpMQ/maxresdefault.jpg",
//      "trailer": "https://www.youtube.com/embed/XRm1P7oGpMQ",
//      "summary": "Lấy bối cảnh một khu chung cư cũ đang chờ giải tỏa tại Sài Gòn, Ròm kể câu chuyện về cuộc sống của những người dân lao động nơi đây. Họ đều chơi số đề với hy vọng kiếm được một khoản tiền lớn để đổi đời. Ròm là cậu bé làm “cò đề” để kiếm sống qua ngày, chuyên tư vấn cho người dân những con số may mắn để họ có cơ may trúng đề."
//     },
//     {
//      "title": "Ava",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "director": "Tate Taylor",
//      "actor": "Jessica Chastain, Colin Farrell",
//      "genre": "Hành động, Tội phạm, Tâm lý",
//      "country": "Mỹ",
//      "openDate": "25/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/18/ava-poster_1600416491387.jpg",
//      "trailer": "",
//      "summary": "Vì phạm vào điều cấm kỵ với công việc, nữ sát thủ Ava từ kẻ đi săn thành con mồi, phải vất vả trốn tránh truy đuổi. Cô nàng buộc phải sử dụng tất cả kỹ năng bao năm tích lũy để sinh tồn."
//     },
//     {
//      "title": "Zombie Mansion",
//      "title_local": "Dinh Thự Xác Sống",
//      "rating": "c18",
//      "length": "120",
//      "genre": "Kinh dị, Tội phạm",
//      "director": "Kimura Hisashi",
//      "actor": "Kamiki Ryunosuke , Hamabe Minami, Furukawa Yuki",
//      "country": "Nhật Bản",
//      "producer": "Toho Company, Ltd.",
//      "openDate": "25/9/2020",
//      "poster": "https://galaxycine.vn/media/2020/9/18/image001_1600408818938.jpg",
//      "trailer": "https://www.youtube.com/watch?v=kwAAVsGV_mc",
//      "summary": "Hai thám tử trung học nổi tiếng Hamura Yuzuru và Akechi Kyosuke nhận lời mời đến dinh thự ven hộ để điều tra về vụ mất tích cách đây nhiều năm của một cô gái. Cùng lúc đó, nữ sinh cùng trường và cũng là thám tử tham vọng Kenzaki Hiruko xuất hiện. Cả ba cùng tham gia trại hè và ở lại dinh thự trên nuối. Không ngờ, họ cùng các lữ khách khác bị xác sống tấn công. Giữa tình cảnh ngàn cân treo sợi tóc ấy, hàng loạt án mạng liên hoàn lại xảy ra. Kẻ sát nhân rốt cuộc là người hay zombie?"
//     },
//     {
//      "title": "Turu: A Wacky Hen",
//      "title_local": "Gà Tây Mê Quẩy",
//      "rating": "c18",
//      "length": "0",
//      "genre": "Gia đình, Hoạt hình",
//      "actor": "Eva Hache, José Mota",
//      "country": "Tây Ban Nha",
//      "director": "Eduardo Gondell, Víctor Monigote",
//      "producer": "Argentina Sono Film S.A.C.I",
//      "openDate": "1/10/2020",
//      "poster": "https://www.cgv.vn/media/catalog/product/cache/1/image/1800x/71252117777b696995f01934522c402d/p/o/poster_ga_tay_me_quay_9_1_.jpg",
//      "trailer": "https://www.youtube.com/embed/JXR8WoQyWTw",
//      "summary": "Sinh ra với sự khác biệt, cô gà mái Turu không thể đẻ trứng như các bạn gà mái khác và luôn mang trong lòng sự tự tin về bản thân. Cuộc đời của Turu bước sang một trang mới khi cô gà bé nhỏ được nhận nuôi bởi Isabel, một giáo viên âm nhạc đã nghỉ hưu."
//     },
//     {
//      "title": "Sài Gòn Trong Cơn Mưa",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "country": "Việt Nam",
//      "genre": "Lãng mạn, Tâm lý",
//      "actor": "Avin Lu, Hồ Thu Anh",
//      "director": "Lê Minh Hoàng",
//      "openDate": "2/10/2020",
//      "poster": "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/s/_/s_i_g_n_trong_c_n_m_a_2.jpg",
//      "trailer": "https://www.youtube.com/embed/F3oWWo8B_ks",
//      "summary": "'Sài Gòn Trong Cơn Mưa' là câu chuyện về tình yêu & ước mơ của những người trẻ tứ xứ tìm thấy nhau giữa Sài Gòn và rồi lạc mất nhau cũng ở giữa Sài Gòn. Còn bạn? Liệu đã gặp được ‘thanh xuân’ của mình dưới cơn mưa đầu mùa nào hay chưa?"
//     },
//     {
//      "title": "Vô Diện Sát Nhân",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "actor": "Phương Anh Đào, Hiếu Nguyễn, Oanh Kiều",
//      "genre": "Kinh dị",
//      "country": "Việt Nam",
//      "producer": "Điền Quân",
//      "openDate": "9/10/2020",
//      "poster": "https://galaxycine.vn/media/2020/1/21/vdsn---teaser-poster---small-file_1579600173941.png",
//      "trailer": "https://www.youtube.com/embed/8efH5QWJ334",
//      "summary": "Liên tục mơ thấy bị một kẻ sát nhân không mặt mũi giết hàng đêm, cuộc sống của Phương Anh bị xáo trộn. Thế nhưng, điều kinh hoàng hơn còn xảy ra, khi tên Vô Diện Sát Nhân bước ra đời thực và truy sát cô. Hắn thực sự tồn tại hay chỉ là nỗi ám ảnh của Phương Anh?"
//     },
//     {
//      "title": "Trái Tim Quái Vật",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "director": "Tạ Nguyên Hiệp",
//      "country": "Việt Nam",
//      "genre": "Ly kì, Tâm lý",
//      "producer": "Wepro",
//      "actor": "Hoàng Thùy Linh, Trịnh Thăng Bình, Hứa Vĩ Văn, B Trần",
//      "openDate": "16/10/2020",
//      "poster": "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/t/r/tr_i_tim_qu_i_v_t_-_teaser_poster_-_kc_16102020_-_website_1_.jpg",
//      "trailer": "https://www.youtube.com/embed/CGSUjKAQVwM",
//      "summary": "‘Trái Tim Quái Vật’ là một câu chuyện đậm chất thriller kể về Khánh (Hoàng Thùy Linh) – một người mẹ đơn thân với khao khát được sống và làm ăn lương thiện nhưng không may vướng vào vòng xoáy tội ác. Bị tình nghi là kẻ giết người tại khu chung cư của mình, Khánh bị dồn đến bước đường cùng và phải ôm con trai bỏ trốn. Câu chuyện càng trở nên phức tạp hơn khi phát hiện hàng loạt vụ án mạng khác cùng sự xuất hiện của Lâm (B Trần), ông Bé (Hứa Vĩ Văn) và Dustin (Trịnh Thăng Bình). Đến tận cùng tội ác, liệu điều gì đang ẩn giấu đằng sau và ai mới là người mang “Trái Tim Quái Vật”?"
//     },
//     {
//      "title": "Candyman",
//      "title_local": "Sát Nhân Trong Gương",
//      "rating": "c18",
//      "length": "0",
//      "country": "Mỹ",
//      "actor": "Yahya Abdul-Mateen II, Teyonah Parris",
//      "director": "Nia DaCosta",
//      "genre": "Kinh dị, Ly kì",
//      "producer": "Metro-Goldwyn-Mayer (MGM), Universal",
//      "openDate": "16/10/2020",
//      "poster": "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/c/d/cdm_digital1sheet_intl_vie_1_.jpg",
//      "trailer": "https://www.youtube.com/embed/kCd4tFfE51o",
//      "summary": "Từ lúc nào không ai hay biết, các dự án nhà ở tại khu Cabrini-Green ở Chicago đã bị khủng bố bởi câu chuyện truyền miệng về một kẻ giết người siêu nhiên với chiếc tay móc câu. Hắn có thể dễ dàng được triệu tập nếu bạn dám nhắc lại tên hắn năm lần trước gương. Ngày nay, một thập kỷ sau khi tòa tháp Cabrini cuối cùng bị phá hủy, nghệ sĩ thị giác Anthony McCoy và người yêu của anh, giám đốc phòng trưng bày Brianna Cartwright di chuyển vào một căn hộ gác xép sang trọng ở Cabrini, giờ đây được cải tạo lại và định cư bởi thế hệ người trẻ năng động. Khi sự nghiệp vẽ tranh của Anthony đang trên bờ vực đình trệ, cuộc gặp gỡ tình cờ với một cư dân cũ của khu Cabrini-Green phơi bày cho Anthony sự thật kinh hoàng về câu chuyện Candyman. Lo lắng để duy trì vị thế của mình trong giới nghệ thuật Chicago, Anthony bắt đầu phát hiện những chi tiết rùng rợn trong xưởng vẽ của mình và anh cũng lấy chúng làm cảm hứng cho các tác phẩm mới. Anh không hề hay biết những điều này đang vô tình mở ra một cánh cửa dẫn tới quá khứ phức tạp, đưa anh tới định mệnh của chính mình. Từ đó anh dần trở nên mất tỉnh táo và rơi sâu hơn vào vòng xoáy bạo lực đáng sợ."
//     },
//     {
//      "title": "Black Widow",
//      "title_local": "Góa Phụ Đen",
//      "rating": "c18",
//      "length": "0",
//      "actor": "Scarlett Johansson, Florence Pugh, Rachel Weisz",
//      "country": "Mỹ",
//      "genre": "Hành động, Giả Tưởng, Phiêu lưu",
//      "producer": "Marvel Studios",
//      "director": "Cate Shortland",
//      "openDate": "6/11/2020",
//      "poster": "https://image.lag.vn/upload/news/20/02/04/bw_online_char_scarlett_v5_lg_xj_NLTP.jpg",
//      "trailer": "https://www.youtube.com/embed/Y55qU93nT7U",
//      "summary": "Phần phim riêng của Natasha Romanoff bất ngờ tung teaser chính thức với những cảnh hành động mãn nhãn, mang đậm chất điệp viên. Bên cạnh đó, phần phim này cũng sẽ hé lộ quá khứ đen tối và quá trình biến cô trở thành một Black Widow."
//     },
//     {
//      "title": "No Time to Die",
//      "title_local": "Không Phải Lúc Chết",
//      "rating": "c18",
//      "length": "0",
//      "producer": "Metro-Goldwyn-Mayer (MGM)",
//      "actor": "Daniel Craig, Rami Malek, Naomie Harris, Léa Seydoux, Ana de Armas",
//      "country": "Mỹ",
//      "director": "Cary Joji Fukunaga",
//      "genre": "Hành động, Phiêu lưu, Ly kì",
//      "openDate": "12/11/2020",
//      "poster": "https://cdnmedia.thethaovanhoa.vn/Upload/leenEplQKY7jsunvYUYgg/files/2020/01/craig1.jpg",
//      "trailer": "https://www.youtube.com/embed/BIhNsAtPbPI",
//      "summary": "Phần 25 của bộ phim điệp viên huyền thoại 007 sẽ tiếp nối câu chuyện về James Bond cùng những pha hành động táo bạo và hoành tráng hơn bao giờ hết"
//     },
//     {
//      "title": "Chị Mười Ba: 3 Ngày Sinh Tử",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "country": "Việt Nam",
//      "director": "Võ Thanh Hòa",
//      "producer": "Galaxy M&E",
//      "genre": "Hành động",
//      "openDate": "18/12/2020",
//      "poster": "https://touchcinema.com/uploads/470x700-teaser-poster.jpg",
//      "trailer": "https://www.youtube.com/embed/jYSojHD7i6Q",
//      "summary": "Kiếp giang hồ, vào dễ khó ra. Những tưởng sau khi lật đổ ông trùm Hắc Hổ, đồng thời đập tan âm mưu thâm độc của Anh Hai, Chị Mười Ba cùng An Cư Nghĩa Đoàn đã có thể yên ổn làm ăn. Thế nhưng, cuộc đời mà, cái quái gì cũng đều xảy ra được. Những kẻ thù mới lại tiếp tục xuất hiện, khiến cho cuộc sống của anh em An Cư Nghĩa Đoàn rúng động thêm lần nữa. Chị Mười Ba đã nhập cuộc trở lại và… bầm dập hơn xưa."
//     },
//     {
//      "title": "Wonder Woman 1984",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "actor": "Gal Gadot, Pedro Pascal, Chris Pine",
//      "director": "Patty Jenkins",
//      "country": "Mỹ",
//      "producer": "Warner Bros",
//      "genre": "Hành động, Phiêu lưu, Giả Tưởng",
//      "openDate": "25/12/2020",
//      "poster": "https://cdn1-www.comingsoon.net/assets/uploads/gallery/wonder-woman-2/ww1984_0.jpg",
//      "trailer": "https://www.youtube.com/embed/XW2E2Fnh52w",
//      "summary": "Lấy bối cảnh năm 1984, 66 năm sau sự kiện diễn ra Thế Chiến thứ I (1918) ở phần phim đầu tiên, Wonder Woman tái hợp với người yêu tưởng chừng đã qua đời Steve Trevor, đồng thời đương đầu với hai kẻ thù mới là Max Lord và The Cheetah."
//     },
//     {
//      "title": "Lật Mặt: 48H",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "genre": "Hành động",
//      "country": "Việt Nam",
//      "director": "Lý Hải",
//      "actor": "Ốc Thanh Vân, Huỳnh Đông, Mạc Văn Khoa, Võ Thành Tâm",
//      "openDate": "12/2/2021",
//      "poster": "https://galaxycine.vn/media/2020/5/15/teaserposer-48h_1589529329248.jpg",
//      "trailer": "https://www.youtube.com/watch?v=PEEIle280jM",
//      "summary": "Một gia đình bị truy đuổi giữa vùng sông nước. Cơ hội nào cho người đàn ông cứu lấy vợ con khỏi bọn xã hội đen máu mặt?"
//     },
//     {
//      "title": "The King's Man",
//      "title_local": "Kingsman: Khởi Nguồn",
//      "rating": "c18",
//      "length": "0",
//      "producer": "20th Century Fox",
//      "actor": "Gemma Arterton, Harris Dickinson, Ralph Fiennes",
//      "country": "Anh",
//      "director": "Matthew Vaughn",
//      "genre": "Hành động",
//      "openDate": "26/2/2021",
//      "poster": "https://i.imgur.com/vb1T8tW.jpg",
//      "trailer": "https://www.youtube.com/embed/__RdchzWCVA",
//      "summary": "Kingsman: Khởi Nguồn là phần tiền truyện của loạt phim Mật vụ Kingsman, xoay quanh quá trình hình thành và phát triển của tổ chức mật vụ nổi tiếng bậc nhất màn ảnh rộng này. Đứng trước một kế hoạch tiêu diệt hàng triệu người do một nhóm những bậc thầy ác nhân và bạo chúa khởi xướng; một điệp viên đầy kinh nghiệm, cùng với sự giúp đỡ của con trai và các cộng sự đáng tin cậy của mình, buộc phải chạy đua với thời gian ngăn chặn âm mưu đó."
//     },
//     {
//      "title": "Fast & Furious 9: The Fast Saga",
//      "title_local": "Quá Nhanh Quá Nguy Hiểm 9",
//      "rating": "c18",
//      "length": "0",
//      "genre": "Hành động, Tội phạm",
//      "director": "Justin Lin",
//      "country": "Mỹ",
//      "producer": "Universal",
//      "actor": "Vin Diesel, John Cena, Charlize Theron",
//      "openDate": "2/4/2021",
//      "poster": "https://galaxycine.vn/media/2020/2/3/300x450_1580700110135.jpg",
//      "trailer": "https://www.youtube.com/watch?v=LdprCQdFlfM",
//      "summary": "Fast & Furious 9 nói về trận chiến mới giữa Dom và những người đồng đội của mình. Lần này ngoại trừ nữ phản diện quen thuộc Cipher thì phim có thêm sự xuất hiện của nhân vật Jacob - em trai của Dom."
//     },
//     {
//      "title": "Tà Năng Phan Dũng",
//      "title_local": "",
//      "rating": "c18",
//      "length": "0",
//      "genre": "Phiêu lưu",
//      "director": "Trần Hữu Tấn",
//      "producer": "ProductionQ - Creative House",
//      "country": "Việt Nam",
//      "actor": "Huỳnh Thanh Trực, Trần Phong",
//      "openDate": "21/4/2021",
//      "poster": "https://galaxycine.vn/media/2020/6/10/tnpd300x450_1591759881783.jpg",
//      "trailer": "https://www.youtube.com/watch?v=a7HSLTWLm2U",
//      "summary": "Phim được thực hiện dựa trên các sự kiện có thật xảy ra tại một trong những cung đường trekking nổi tiếng nhất nước ta: Tà Năng - Phan Dũng. Đây cũng là tác phẩm đầu tiên của điện ảnh Việt Nam làm về chủ đề sinh tồn."
//     },
//     {
//      "title": "A Quiet Place 2",
//      "title_local": "Vùng Đất Câm Lặng 2",
//      "rating": "c18",
//      "length": "0",
//      "director": "John Krasinski",
//      "genre": "Kinh dị",
//      "country": "Mỹ",
//      "producer": "Paramount Pictures",
//      "actor": "Emily Blunt, Cillian Murphy, Noah Jupe",
//      "openDate": "23/4/2021",
//      "poster": "https://galaxycine.vn/media/2020/5/15/aqp2-poster-vdcl-2-1_1589528481304.jpg",
//      "trailer": "",
//      "summary": "A Quiet Place 2 là bộ phim kinh dị được mong chờ nhất 2020. Mất đi người chồng người cha trụ cột, mẹ góa con côi nhà Abbott sẽ ra sao ở thế giới đầy bọn quái vật? Chắc chắn mẹ con Evelyn Abbott sẽ phải trải qua rất nhiều nguy hiểm để tìm cách sống còn. Liệu biến cố gì sẽ xảy ra ở phần 2?"
//     },
//     {
//      "title": "Minions: The Rise of Gru",
//      "title_local": "Minions: Sự Trỗi Dậy Của Gru",
//      "rating": "c18",
//      "length": "0",
//      "country": "Mỹ",
//      "director": "Kyle Balda",
//      "actor": "Steve Carell, Julie Andrews",
//      "genre": "Hoạt hình",
//      "producer": "Illumination Entertainment",
//      "openDate": "2/7/2021",
//      "poster": "https://galaxycine.vn/media/2020/2/13/ewewe_1581587057402.jpg",
//      "trailer": "",
//      "summary": "Minions - Những Quả Chuối Vàng biết đi sẽ trở lại trong câu chuyện chưa kể về tuổi thơ của Gru - cậu bé mười hai tuổi mơ được trở thành ác nhân xuất sắc nhất thế giới."
//     }
//    ]

// movies.forEach(movie => {
//     let dateStr = movie.openDate

//     let day = dateStr.split('/')[0]
//     let month = dateStr.split('/')[1]
//     let year = dateStr.split('/')[2]

//     movie.openDate = new Date(Date.UTC(year,month-1,day))
// })

// console.log(JSON.stringify(movies));
let openDate = '2021-02-12T00:00:00.000Z'
let d = new Date(openDate)
console.log(d instanceof Date);